//
// Peano4 data file
// Generated by Peano's Python API
// www.peano-framework.org
// This is generated. Be careful with adding your own stuff
//
#ifndef __EXAMPLES_EXAHYPE2_CCZ4_CONSTANTS__
#define __EXAMPLES_EXAHYPE2_CCZ4_CONSTANTS__


#include <string>


#include <bitset>



namespace examples{
namespace exahype2{
namespace ccz4{

  const std::initializer_list<double> DomainOffset = {-0.5,-0.5,-0.5};
  const std::initializer_list<double> DomainSize = {1.0,1.0,1.0};
  constexpr auto TerminalTime = 0.002;
  constexpr auto FirstPlotTimeStamp = 0.0;
  constexpr auto TimeInBetweenPlots = 0;
  const std::bitset<3> PeriodicBC = 0;
  constexpr auto CCZ4GLMc0 = 1.5;
  constexpr auto CCZ4GLMc = 1.0;
  constexpr auto CCZ4GLMd = 2.0;
  constexpr auto CCZ4GLMepsA = 1.0;
  constexpr auto CCZ4GLMepsP = 1.0;
  constexpr auto CCZ4GLMepsD = 1.0;
  constexpr auto CCZ4itau = 1.0;
  constexpr auto CCZ4k1 = 0.1;
  constexpr auto CCZ4k2 = 0.1;
  constexpr auto CCZ4k3 = 0.1;
  constexpr auto CCZ4eta = 1.0;
  constexpr auto CCZ4f = 0.1;
  constexpr auto CCZ4g = 0.0;
  constexpr auto CCZ4xi = 0.1;
  constexpr auto CCZ4e = 1.0;
  constexpr auto CCZ4c = 1.0;
  constexpr auto CCZ4mu = 0.2;
  constexpr auto CCZ4ds = 1.0;
  constexpr auto CCZ4sk = 0.1;
  constexpr auto CCZ4bs = 0.1;
  constexpr auto CCZ4LapseType = 0;
  const std::string Scenario = "gaugewave-c++";

}
}
}


#endif


